name: login_flutter
description: A flutter login model app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  #flutter_animate: ^4.3.0
  url_launcher: ^6.2.2  # Use the latest version
  flutter_native_splash: ^2.3.4
  #hive: ^2.2.3
  #hive_flutter: ^1.1.0
  #fluttertoast: ^8.2.4
  introduction_screen: ^3.1.12
  card_swiper: ^3.0.1
  webview_flutter: ^2.0.13
  flutter_animate: ^4.4.1
  shared_preferences: ^2.2.2
  #video_player: ^2.2.17
  #flutter_widget_from_html: ^0.9.1

dev_dependencies:flutter:
  uses-material-design: true
  flutter_native_splash: ^2.3.4

  assets:
         
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#42a5f5"



flutter:
  uses-material-design: true

  assets:
    - assets/Logo.png
    - assets/category1.png
    - assets/category2.png
    - assets/category3.png
    - assets/category4.png
    - assets/category5.png
    - assets/background.jpg
    - assets/Gallery/gallery1.jpg
    - assets/Gallery/gallery2.jpg
    - assets/Gallery/gallery3.jpg
    
